load("@buck2-haskell//:defs.bzl", "haskell_toolchain_library")
load("@toolchains//:haskell_all.bzl", "haskell_toolchain_all")

# Boot libraries ship in the locally built GHC's global package db.
[haskell_toolchain_library(
    name = lib,
    visibility = ["//..."],
) for lib in [
    "array",
    "base",
    "binary",
    "bytestring",
    "containers",
    "deepseq",
    "directory",
    "exceptions",
    "filepath",
    "ghc",
    "ghc-boot",
    "os-string",
    "process",
    "text",
    "time",
    "transformers",
    "unix",
]]

# Third-party dependencies come from the cabal store db.
[haskell_toolchain_library(
    name = lib,
    visibility = ["//..."],
) for lib in [
    "aeson",
    "async",
    "extra",
    "file-io",
    "flatparse",
    "generic-lens",
    "ghc-paths",
    "grapesy",
    "hashable",
    "hedgehog",
    "lens",
    "mtl",
    "lens-family",
    "optparse-applicative",
    "proto-lens",
    "split",
    "tasty",
    "tasty-hedgehog",
    "temporary",
    "typed-process",
    "vector",
]]
