load("@buck2-haskell//:defs.bzl", "haskell_toolchain_library")
load("@toolchains//:haskell_all.bzl", "haskell_toolchain_all")
load("@toolchains//:libs.bzl", "toolchain_libraries")

[haskell_toolchain_library(
    name = lib,
    visibility = ["//..."],
) for lib in [
    "aeson",
    "array",
    "async",
    "base",
    "binary",
    "bytestring",
    "containers",
    "deepseq",
    "directory",
    "exceptions",
    "filepath",
    "file-io",
    "flatparse",
    "ghc",
    "ghc-boot",
    "ghc-paths",
    "grapesy",
    "hashable",
    "lens-family",
    "optparse-applicative",
    "os-string",
    "process",
    "proto-lens",
    "split",
    "text",
    "time",
    "transformers",
    "unix",
    "vector",
]]

python_bootstrap_binary(
    name = "generate_toolchain_libs",
    main = "generate_toolchain_libs.py",
)

# [haskell_toolchain_library(name = lib, visibility = ["//..."]) for lib in toolchain_libraries]
