-- | Description: Standalone benchmark (@compare-eviction@) comparing lazy bytecode cache memory behavior with and
-- without eviction ('Types.FeatureFlags.lazyByteCodeCacheLimit'), measuring actual GHC heap residency ("live bytes",
-- via 'GHC.Stats.getRTSStats') rather than the coarse BCO-count proxy used by
-- 'ConcurrentInterpretedTest.test_bcoEvictionConcurrentInterpreted'.
--
-- The scenario mirrors that test's shape (a shared module imported by every leaf, plus one large per-leaf helper
-- module, spliced against via Template Haskell and executed through the production eval path), but runs many more
-- iterations sequentially in a single worker session, each iteration adding a *new* leaf with its own large helper
-- module. Without eviction, the tracked bytecode (and the live heap bytes behind it) grows without bound as more
-- leaves accumulate; with eviction enabled, older leaves' bytecode is unloaded once the tracked size exceeds a
-- configured limit, and live bytes should stay roughly within a bound instead of growing linearly with iteration
-- count.
--
-- Each helper module is generated by 'Test.Source.fatModuleSource': it contains @--functions@ top-level
-- @'Int' -> 'Int'@ functions each with @--case-arms@ integer case alternatives.  Empirically, the count of
-- functions (top-level bindings, hence distinct BCOs) is the dominant lever on the freed heap per evicted module,
-- not the arms per function -- see the haddock on 'Test.Source.fatModuleSource' for the measurements behind this.
-- The defaults below were chosen to give a heap difference in the tens of megabytes within a benchmark run of
-- well under a minute.
module GhcServer.CompareEviction (
  main_compareEviction,
) where

import Control.Concurrent.MVar (readMVar)
import Data.Foldable (traverse_)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import GHC.Stats (GCDetails (..), RTSStats (..), getRTSStats)
import Numeric.Natural (Natural)
import Options.Applicative (
  Parser,
  ParserInfo,
  auto,
  execParser,
  fullDesc,
  header,
  help,
  helper,
  info,
  long,
  metavar,
  option,
  progDesc,
  short,
  value,
  (<**>),
  )
import System.Mem (performMajorGC)
import Test.Build (metadataArgs, runCompile, runEvaluate, runMetadata)
import Test.Bytecode (enableLazyByteCode)
import Test.Data.Env (SessionEnv (..), TestEnv (..))
import Test.Data.Project (BuildModule (..), GenUnit (..), ModuleKey (..), ModuleSource (..), UnitKey)
import Test.Data.Scheduler (RequestResult (..))
import Test.Env (acquireTestEnv, newSessionEnv, releaseTestEnv)
import Test.Path (testFunctionName)
import Test.Source (writeFatModuleSource, writeProjectSources, writeTestModuleSources)
import Types.Args (Args (..))
import Types.Env (Env (..))
import Types.FeatureFlags (FeatureFlags (..))
import Types.State (WorkerState (..))
import Types.State.Make (BcoCacheEntry (..), MakeState (..))

-- ---------------------------------------------------------------------------
-- Configuration
-- ---------------------------------------------------------------------------

data EvictionCompareConfig =
  EvictionCompareConfig {
    iterations :: Int,
    -- | Number of @Int -> Int@ case-expression functions per helper module.  Each is a distinct top-level binding
    -- (hence a distinct BCO), and is the dominant lever on freed heap per evicted module -- see
    -- 'Test.Source.fatModuleSource' for measurements showing this outweighs 'caseArms'.
    functions :: Int,
    -- | Number of case alternatives per fat function.  Each alternative becomes a 'TESTEQ_I' instruction in the
    -- BCO, so the instruction-array size scales linearly with this value, but its contribution to freed heap is
    -- minor compared to 'functions'; kept greater than 1 only so each function is a genuine multi-way case.
    caseArms :: Int,
    keepFactor :: Int
  }
  deriving stock (Show)

configParser :: Parser EvictionCompareConfig
configParser =
  EvictionCompareConfig
    <$> option auto (long "iterations" <> short 'n' <> metavar "N"
          <> help "Number of leaves to build and evaluate sequentially" <> value 12)
    <*> option auto (long "functions" <> short 'f' <> metavar "N"
          <> help "Fat functions per helper module (number of BCOs per helper; dominant size lever)" <> value 1000)
    <*> option auto (long "case-arms" <> short 'c' <> metavar "N"
          <> help "Case alternatives per fat function (minor effect on size; keeps functions non-trivial)" <> value 5)
    <*> option auto (long "keep-factor" <> short 'k' <> metavar "N"
          <> help "Eviction limit expressed as a multiple of one iteration's tracked cache size" <> value 3)

configParserInfo :: ParserInfo EvictionCompareConfig
configParserInfo =
  info (configParser <**> helper)
    (fullDesc
    <> progDesc "Compare live-byte memory usage of the lazy bytecode cache with and without eviction"
    <> header "compare-eviction - bytecode eviction memory benchmark")

-- ---------------------------------------------------------------------------
-- Scenario project shape
-- ---------------------------------------------------------------------------

-- | Number of trivial 'Int' bindings in the shared module.  The shared module is never evicted, so its size
-- only contributes to the fixed baseline heap; keeping it small avoids obscuring the per-leaf difference.
sharedBindings :: Int
sharedBindings = 10

-- | Unit @0@'s single module, shared (imported and spliced against) by every leaf.
sharedKey :: ModuleKey
sharedKey = ModuleKey {unit = 0, number = 0, errorVariant = Nothing}

sharedModule :: BuildModule
sharedModule =
  BuildModule {key = sharedKey, deps = mempty, th = False, bindings = sharedBindings, extDeps = mempty}

sharedUnit :: GenUnit BuildModule
sharedUnit =
  GenUnit {key = 0, depUnits = mempty, modules = [sharedModule]}

-- | A leaf's dedicated fat helper module (module number @1@; the leaf's TH test module is number @0@).
-- The helper is compiled to large BCOs via 'writeFatModuleSource'; its 'BuildModule' bindings count is
-- a placeholder only (the 'ModuleSource' it carries is never used for source generation here).
helperKey :: UnitKey -> ModuleKey
helperKey leaf = ModuleKey {unit = leaf, number = 1, errorVariant = Nothing}

helperModule :: UnitKey -> BuildModule
helperModule leaf =
  BuildModule {key = helperKey leaf, deps = mempty, th = False, bindings = 1, extDeps = mempty}

-- | A leaf's TH-splicing test module, depending on both the shared module and this leaf's own helper module.
testKey :: UnitKey -> ModuleKey
testKey leaf = ModuleKey {unit = leaf, number = 0, errorVariant = Nothing}

testModule :: UnitKey -> BuildModule
testModule leaf =
  BuildModule {
    key = testKey leaf,
    deps = Set.fromList [sharedKey, helperKey leaf],
    th = True,
    bindings = 1,
    extDeps = mempty
  }

leafUnit :: UnitKey -> BuildModule -> BuildModule -> GenUnit BuildModule
leafUnit leaf helperMod test =
  GenUnit {key = leaf, depUnits = Set.singleton 0, modules = [helperMod, test]}

moduleSourceOf :: BuildModule -> ModuleSource
moduleSourceOf BuildModule {deps, th, bindings, extDeps} =
  ModuleSource {deps = Set.toList deps, th, bindings, extDeps}

-- ---------------------------------------------------------------------------
-- Measurement
-- ---------------------------------------------------------------------------

-- | One iteration's live-byte residency (forced major GC, then 'GHC.Stats.getRTSStats') and the tracked bytecode
-- cache size for cross-reference against the coarse proxy measure.
data IterationMeasurement =
  IterationMeasurement {
    iteration :: Int,
    liveBytes :: Word,
    trackedCacheSize :: Int,
    cacheEntries :: Int
  }

measure :: Int -> Env -> IO IterationMeasurement
measure iteration env = do
  performMajorGC
  stats <- getRTSStats
  WorkerState {make} <- readMVar env.state
  let entries = Map.elems make.bcoCache
  pure IterationMeasurement {
    iteration,
    liveBytes = fromIntegral stats.gc.gcdetails_live_bytes,
    trackedCacheSize = sum ((.size) <$> entries),
    cacheEntries = length entries
  }

-- | Build and evaluate one leaf (metadata + helper compile + TH test evaluation), then take a measurement.
runIteration ::
  SessionEnv ->
  (GenUnit BuildModule -> Args) ->
  (ModuleKey -> (Args, Set.Set Natural)) ->
  EvictionCompareConfig ->
  Int ->
  IO IterationMeasurement
runIteration sessionEnv mkMetaArgs mkArgs config i = do
  let leaf = fromIntegral (i + 1) :: UnitKey
      helperMod = helperModule leaf
      test = testModule leaf
      unit = leafUnit leaf helperMod test
  writeFatModuleSource sessionEnv.sourceDir config.functions config.caseArms (helperKey leaf)
  writeTestModuleSources sessionEnv.sourceDir (Map.singleton (testKey leaf) (moduleSourceOf test))
  metaResult <- runMetadata sessionEnv mkMetaArgs unit
  compileResult <- runCompile sessionEnv mkArgs (helperKey leaf)
  evalResult <- runEvaluate sessionEnv mkArgs (testFunctionName (testKey leaf)) (testKey leaf)
  checkResults i [("metadata", metaResult), ("compile", compileResult), ("evaluate", evalResult)]
  measure i sessionEnv.env

-- | Report (rather than silently ignore) any unsuccessful worker task, since a failed compile/eval would otherwise
-- masquerade as an empty bytecode cache.
checkResults :: Int -> [(String, RequestResult)] -> IO ()
checkResults i =
  traverse_ report
  where
    report (label, result) =
      case result of
        RequestSuccess -> pure ()
        failure -> putStrLn ("iteration " ++ show i ++ " " ++ label ++ " FAILED: " ++ show failure)

-- ---------------------------------------------------------------------------
-- Scenario runner
-- ---------------------------------------------------------------------------

-- | Run the full scenario for a given eviction limit (or 'Nothing' to disable eviction): build the shared module
-- once, then @iterations@ leaves sequentially, measuring live bytes after each.
runScenario :: EvictionCompareConfig -> Maybe Int -> IO [IterationMeasurement]
runScenario config evictionLimit = do
  testEnv <- acquireTestEnv
  measurements <- runWithEnv testEnv
  releaseTestEnv testEnv
  pure measurements
  where
    runWithEnv :: TestEnv -> IO [IterationMeasurement]
    runWithEnv testEnv = do
      sessionEnv <- withLimit <$> newSessionEnv (enableLazyByteCode testEnv)
      let mkMetaArgs = metadataArgs sessionEnv False
          -- Include the same bytecode-output flags as the metadata step so that compiled home modules carry
          -- 'homeMod_bytecode' in their 'HomeLinkable', making them visible to the BCO cache tracker when
          -- Template Haskell splices resolve their link dependencies via 'linkablesResolve'.
          -- Without these flags the GHC session uses default DynFlags (object-code only), producing linkables
          -- with no BCO parts, and 'touchBcoCache' is always a no-op.
          bcodeDynFlags :: [String]
          bcodeDynFlags = ["-fbyte-code-and-object-code", "-fprefer-byte-code", "-dynamic", "-fPIC", "-osuf", "dyn_o", "-hisuf", "dyn_hi"]
          mkArgs :: ModuleKey -> (Args, Set.Set Natural)
          mkArgs _ = (sessionEnv.shared.baseArgs {ghcOptions = bcodeDynFlags}, mempty)
      writeProjectSources sessionEnv.sourceDir (Map.singleton sharedKey (moduleSourceOf sharedModule))
      sharedMetaResult <- runMetadata sessionEnv mkMetaArgs sharedUnit
      sharedCompileResult <- runCompile sessionEnv mkArgs sharedKey
      checkResults (-1) [("shared metadata", sharedMetaResult), ("shared compile", sharedCompileResult)]
      mapM (runIteration sessionEnv mkMetaArgs mkArgs config) [0 .. config.iterations - 1]

    withLimit sessionEnv =
      sessionEnv {
        shared = sessionEnv.shared {
          baseArgs = sessionEnv.shared.baseArgs {
            features = sessionEnv.shared.baseArgs.features {lazyByteCodeCacheLimit = evictionLimit}
          }
        }
      }

-- ---------------------------------------------------------------------------
-- Reporting
-- ---------------------------------------------------------------------------

showMB :: Word -> String
showMB bytes =
  showFixed2 (fromIntegral bytes / 1_000_000 :: Double) ++ " MB"

showFixed2 :: Double -> String
showFixed2 d =
  show whole ++ "." ++ frac
  where
    centis = round (d * 100) :: Integer
    whole = div centis 100
    fracN = mod (abs centis) 100
    frac = (if fracN < 10 then "0" else "") ++ show fracN

printSeries :: String -> [IterationMeasurement] -> IO ()
printSeries label series = do
  putStrLn ""
  putStrLn ("=== " ++ label ++ " ===")
  putStrLn (padRight 10 "Iter" ++ padLeft 14 "Live bytes" ++ padLeft 16 "Tracked cache" ++ padLeft 10 "Entries")
  traverse_ printRow series
  where
    printRow m =
      putStrLn (
        padRight 10 (show m.iteration)
          ++ padLeft 14 (showMB m.liveBytes)
          ++ padLeft 16 (show m.trackedCacheSize)
          ++ padLeft 10 (show m.cacheEntries)
        )

padRight :: Int -> String -> String
padRight n s = s ++ replicate (max 0 (n - length s)) ' '

padLeft :: Int -> String -> String
padLeft n s = replicate (max 0 (n - length s)) ' ' ++ s

-- | Compare first-half vs. second-half average live bytes for each series: a series with eviction working correctly
-- should show the two halves close together (bounded), while an unbounded series should show the second half
-- noticeably higher than the first.
printSummary :: [IterationMeasurement] -> [IterationMeasurement] -> IO ()
printSummary withoutEviction withEviction = do
  putStrLn ""
  putStrLn "=== Summary ==="
  reportFinal "Without eviction" withoutEviction
  reportFinal "With eviction" withEviction
  where
    reportFinal label series =
      case series of
        [] -> pure ()
        _ -> do
          let half = max 1 (length series `div` 2)
              firstHalf = take half series
              secondHalf = drop half series
              avgLive xs = sum ((.liveBytes) <$> xs) `div` fromIntegral (max 1 (length xs))
          putStrLn (
            label ++ ": first-half avg live " ++ showMB (avgLive firstHalf)
              ++ ", second-half avg live " ++ showMB (avgLive secondHalf)
            )

-- ---------------------------------------------------------------------------
-- Main entry point
-- ---------------------------------------------------------------------------

main_compareEviction :: IO ()
main_compareEviction = do
  config <- execParser configParserInfo
  putStrLn ("Iterations: " ++ show config.iterations ++ ", fat functions/module: " ++ show config.functions ++ ", case arms/function: " ++ show config.caseArms)

  withoutEviction <- runScenario config Nothing
  printSeries "Without eviction (lazyByteCodeCacheLimit = Nothing)" withoutEviction

  let firstIterationSize = maybe 0 (.trackedCacheSize) (lookupIteration 0 withoutEviction)
      limit = max 1 (firstIterationSize * config.keepFactor)
  putStrLn ""
  putStrLn ("Derived eviction limit: " ++ show limit ++ " (keep-factor " ++ show config.keepFactor
    ++ " x first-iteration tracked size " ++ show firstIterationSize ++ ")")

  withEviction <- runScenario config (Just limit)
  printSeries ("With eviction (lazyByteCodeCacheLimit = Just " ++ show limit ++ ")") withEviction

  printSummary withoutEviction withEviction
  where
    lookupIteration i = foldr (\ m acc -> if m.iteration == i then Just m else acc) Nothing
