cabal-version: 3.4
name: ghc-ui
version: 0.1
synopsis: Terminal UI for ghc-server
license: MIT
build-type: Simple

common all
  ghc-options: -Wall -Widentities -Wincomplete-uni-patterns -Wmissing-deriving-strategies -Wredundant-constraints -Wunused-type-patterns -Wunused-packages
  default-language: GHC2021
  default-extensions:
    BlockArguments,
    DataKinds,
    DerivingStrategies,
    DuplicateRecordFields,
    LambdaCase,
    NamedFieldPuns,
    NoFieldSelectors,
    OverloadedLabels,
    OverloadedLists,
    OverloadedRecordDot,
    OverloadedStrings,
    QuasiQuotes,
    RecordWildCards,
    StrictData,
    TemplateHaskell,
    TypeFamilies
  build-depends:
    base ==4.*

library
  import: all
  hs-source-dirs: lib
  exposed-modules:
    Ghc.Ui.Attr
    Ghc.Ui.App
    Ghc.Ui.Cli
    Ghc.Ui.Data.Log
    Ghc.Ui.Data.Main
    Ghc.Ui.Data.Session
    Ghc.Ui.Data.Sessions
    Ghc.Ui.Data.ServerApi
    Ghc.Ui.Data.ServerHandlers
    Ghc.Ui.Data.ServerProcess
    Ghc.Ui.Data.Tasks
    Ghc.Ui.Data.Project
    Ghc.Ui.Data.Name
    Ghc.Ui.Data.OpLog
    Ghc.Ui.Data.WorkerId
    Ghc.Ui.Event.Log
    Ghc.Ui.Event.Main
    Ghc.Ui.Event.OpLog
    Ghc.Ui.Event.Popup
    Ghc.Ui.Event.Session
    Ghc.Ui.Event.Sessions
    Ghc.Ui.Event.Tasks
    Ghc.Ui.Event.Project
    Ghc.Ui.Render.Format
    Ghc.Ui.GhcDebug
    Ghc.Ui.Monad
    Ghc.Ui.OpLog
    Ghc.Ui.Render.Layer
    Ghc.Ui.Render.Log
    Ghc.Ui.Render.Logo
    Ghc.Ui.Render.Main
    Ghc.Ui.Render.OpLog
    Ghc.Ui.Render.Popup
    Ghc.Ui.Render.Section
    Ghc.Ui.Render.Session
    Ghc.Ui.Render.Sessions
    Ghc.Ui.Render.Target
    Ghc.Ui.Render.Tasks
    Ghc.Ui.Render.Project
    Ghc.Ui.Run
    Ghc.Ui.Server.Api
    Ghc.Ui.Server.Monad
    Ghc.Ui.Server.Process
    Ghc.Ui.Server.Start
    Ghc.Ui.Server.Stop
  build-depends:
    aeson,
    async,
    binary,
    brick,
    buck-worker-internal,
    buck-worker-proto,
    buck-worker-types,
    bytestring,
    containers,
    exceptions,
    extra,
    generic-lens,
    ghc-debug-brick,
    directory,
    filepath,
    fsnotify,
    grapesy,
    lens,
    lifted-async,
    lifted-base,
    mtl,
    network,
    optparse-applicative,
    os-string,
    typed-process,
    text,
    time,
    unix,
    vty

executable ghc-ui
  main-is: Main.hs
  hs-source-dirs: app
  ghc-options:
    -threaded -rtsopts -with-rtsopts=-N -O2
  build-depends:
    ghc-ui
